services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # JVM 메모리 설정
    ports:
      - "9200:9200"  # HTTP 연결 포트
      - "9300:9300"  # 클러스터 노드간 통신 포트
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - esnet

volumes:
  es_data:
    driver: local

networks:
  esnet:
    driver: bridge