spring:
  application:
   name: elastic-search-study
  jpa:
      hibernate:
        ddl-auto: none
      show-sql: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

elasticsearch:
  host: localhost
  port: 9200